### ISSUE TITLE
Not clear that CSS also needed for sidebar to work

### ISSUE THREAD

**Issue by teamrc** [jillix/jQuery-sidebar#10]
I tried creating a blank new HTML file with your instructions provided in README.md.
After a baffling and struggling to see why there was no animations, I had to review your homepage DEMO before I realised that CSS also has to be applied.

I think it would be less confusing if this can be mentioned in the README.md, as well as including a demo.html.

I have created such a demo.html, feel free to pull it if you think it is a good idea. (it certainly was for me!)

**Comment by IonicaBizau** [comment]
Yes, the specific CSS should be added by the application developer. Thanks for contribution! :+1:

**Comment by chrisalcantara** [comment]
FYI. There is still no reference to CSS needed for this to work.

**Comment by IonicaBizau** [comment]
@chrisalcantara Thanks for heads-up!

@silviubogan Can you please add this in the docs? :pray:
