### ISSUE TITLE
Sidebar does not work well when Resized

### ISSUE THREAD

**Issue by teamrc** [jillix/jQuery-sidebar#14]
Currently, sidebar has the range width/height hardcoded.

While it's okay if the sidebar's size stays static, but I encountered issues when closing/opening sidebar after sidebar is resized using jquery's resizable.
https://jqueryui.com/resizable/

It would be great if the sidebar's width/height be dynamic instead of hardcoded.

**Comment by IonicaBizau** [comment]
Sounds like a bug. :bug: 

Could you please create a reproduction page (JSFiddle or so), so I can see what's going on? Thanks!

**Comment by teamrc** [comment]
I would be keen to call this a 'feature request', not a bug. =)

you can replicate it like this.

$('#lhs_toc').resizable()
$("#lhs_toc").sidebar();
now open/close the sidebar.. works great
now resize the sidebar
now open/close the sidebar... and the logic is busted.

**Comment by IonicaBizau** [comment]
Ah, I see what you mean. :+1: 
However, #15 will fix the issue regarding browser window resizing, right?

It's more a bug. :smile:

**Comment by teamrc** [comment]
I can't see browser window resizing causing issues with sidebar.

The issue lies when the sidebar's dimensions (i.e. width/height) is altered using resizable().

**Comment by IonicaBizau** [comment]
It does create issues when the sidebar has percentage size.

**Comment by IonicaBizau** [comment]
Fixed via #15. :sparkles:

**Comment by IonicaBizau** [comment]
> I can't see browser window resizing causing issues with sidebar.

@teamrc The percentage size bug was fixed in #23 (:ship: `3.3.0`). :tada:
