### ISSUE TITLE
How do I get a control button for toggle sidebar

### ISSUE THREAD

**Issue by teamrc** [jillix/jQuery-sidebar#16]
Not a bug this time, a question... which is how I can get a toggle button working?

Here is a demo of what I'm thinking.
http://pupunzi.com/mb.components/mb.extruder/demo/demo.html

**Comment by IonicaBizau** [comment]
Just attach a click handler on your button and, *on click* trigger *sidebar:toggle*:

```js
$(".your-button").on("click", function () {
    $(".some-sidebar").trigger("sidebar:toggle");
})'
```

**Comment by teamrc** [comment]
But how do I ALSO get the button to move together with the sidebar?
A demo is found below.
http://pupunzi.com/mb.components/mb.extruder/demo/demo.html

I guess I can make the HTML control div/button itself a sidebar. 
Just wondering if there is an easier way?

**Comment by IonicaBizau** [comment]
That should be easy with some CSS tricks: http://jsfiddle.net/d106ko82/

**Comment by teamrc** [comment]
That was a ridiculously easy solution. Basically set the button position to be relative. Cheers.

e.g.
$("#btn_div").css("left", 10);
$("#btn_div").css("position", "relative");

**Comment by IonicaBizau** [comment]
:+1: :smile: :tada:
