### ISSUE TITLE
Sidebar shifts to right when a Bootstrap modal is opened

### ISSUE THREAD

**Issue by dlong500** [jillix/jQuery-sidebar#19]
This isn't a huge deal, but it would be nice to be able to avoid having the sidebar shift to the right when a Bootstrap modal is invoked.  Bootstrap removes the scrollbar of the main viewport when a modal is opened, and thus the sidebar gets shifted to the right.  It's not a functional issue, but aesthetically it is distracting.

Given all the magic Bootstrap uses behind the scenes there is no simple CSS fix to prevent the issue without causing other problems.  Is there anything that could be added to allow the sidebar to detect removal of a scrollbar and compensate for that?

**Comment by IonicaBizau** [comment]
If I understood correctly, it's the same issue like when we have a dynamic width sidebar which is closed and the window is resized. Then a little part of the sidebar is shown.

I'm not sure but, we may fix the both issues using `$(window).on("resize", doTheMagic)`.
Would you like to fix this?
