### ISSUE TITLE
How to create a label attached to sidebar to open it?

### ISSUE THREAD

**Issue by biapar** [jillix/jQuery-sidebar#20]
How to create a label attached to sidebar to open it?

**Comment by IonicaBizau** [comment]
Hey!

Could you please tell us more about what you're trying to do?
If you're asking about having the toggle button inside of the sidebar, [here](http://jsfiddle.net/d106ko82/) is an example. /cc #16

**Comment by IonicaBizau** [comment]
@biapar Ping me if you need more help. :smile: Closing for now.
