### ISSUE TITLE
Toggle trigger problem

### ISSUE THREAD

**Issue by unip** [jillix/jQuery-sidebar#21]
Hi. I got a problem here. I use 'toggle' trigger for my sidebar and call a button for trigger the sidebar. The problem is it only works for two click which makes the sidebar open for the first click and close for the second click and doesn't do anything for the third click. It only stay closed at left side. I wrote the script like this:
```javascript
$(document).ready(function(){
	$('#button').click(function(){
		$('#sidebar').sidebar();
		$('#sidebar').trigger('sidebar:toggle');
	});
});
```
Any solution? By the way, thanks for the nice plugin :)

**Comment by IonicaBizau** [comment]
Hey @unip!

The problem in your code is that you initialize the sidebar every time you click the button. You should initialize it once, after the document is ready:

```js
$(document).ready(function(){
    $('#sidebar').sidebar();
    $('#button').click(function(){
        $('#sidebar').trigger('sidebar:toggle');
    });
});
```

If you have any other questions, I'm happy to answer. :smile: :four_leaf_clover: 

[**JSFIDDLE**](http://jsfiddle.net/d106ko82/9/)

**Comment by unip** [comment]
Thank you for the feedback :smile: 
I'll try it right away :+1:
