### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by grafa** [jillix/jQuery-sidebar#24]
Hi there,

can you please add support for bower?

Thanks

**Comment by IonicaBizau** [comment]
I never used bower before, but if anyone of you could add support for you, we would be happy! :sparkles:

**Comment by IonicaBizau** [comment]
@silviubogan is on it. :sparkle:

**Comment by silviubogan** [comment]
@IonicaBizau, I opened this pull request: #25. :smiley:

**Comment by IonicaBizau** [comment]
Bower support landed in `3.3.1` :ship: :tada: Thanks, @silviubogan! :+1:

**Comment by grafa** [comment]
Well done guys! Thanks!

**Comment by IonicaBizau** [comment]
@grafa You're welcome! :+1:
