### ISSUE TITLE
Closing when clicking outside

### ISSUE THREAD

**Issue by celsaad** [jillix/jQuery-sidebar#29]
Could you please add support (or maybe an option) to close the sidebar when clicking outside the sidebar?

(there's a neat solution for that here: http://stackoverflow.com/questions/152975/how-to-detect-a-click-outside-an-element/3028037#3028037 )

**Comment by IonicaBizau** [comment]
Well, that's really easy as custom code. In fact, in the context of the sidebar we don't know what is the _outside_. :crystal_ball: 

An example to get this running on the demo page is (run this in developer tools console):

``` js
$("body").children().not(".sidebars").on("click", function () {
   $(".sidebar").trigger("sidebar:close")
});
```

So, I'm closing this, but if anybody has any ideas, feel free to leave comments. :thought_balloon:
