### ISSUE TITLE
How use isClosed (Boolean) Option?

### ISSUE THREAD

**Issue by pooyamoha** [jillix/jQuery-sidebar#30]
Hi,
In the documentation said there is a boolean indicating sidebar is closed or not name isClosed. I just was wondering if anybody could show me in the code how we can use this boolean and compare that with true or false in the code?

P.S:
isClosed (Boolean): A boolean value indicating if the sidebar is closed or not (default: false).

Thanks!

**Comment by IonicaBizau** [comment]
@pooyamoha That option is to explicitly specify the sidebar state. You don't really want to use it that option as long you are not a mad scientist. :smile:

To keep the sidebar opened or closed by default use the `close` option. The `isClosed` option is more for internal usage. There is probably no good example how to use it from the public side.

**Comment by pooyamoha** [comment]
well , my problem is i need to indicate whether sidebar is open or closed ,  when i use following code in Web browser on my laptop it works fine , but when i use it for Samsung Tizen Web Application project , Sidebar works fine there too , but indicating if the sidebar is opened or closed with following code doesn't work in Samsung Tizen project . so i am trying to do a alternative way to figure out when Jquery-sidebar is opened , when it's not? any idea?

```
$(".my-sidebar").on("sidebar:opened", function () {
// do something on opened
 });
```

P.S : by default Samsung Tizen IDE would add JQuery 1.9.1 library to project , since that version is not the latest one , does it might be the reason?

Thanks!

**Comment by IonicaBizau** [comment]
Use `close:false` to disable the default closing. Can you create a minimal example reproducing your issue?

**Comment by pooyamoha** [comment]
i use above code that i have posted in event listener inside a switch case code.

here is the code , not sure if you could reproduce it without Samsung Tizen SDK but here is part of the regard code:

```
document.addEventListener('keydown', function (e) {
switch (e.keyCode) {
            case 39:
            case 40:
 $(".sidebar.left").on("sidebar:opened", function () {
// this following code only fired if i press other key in remote control so other cases of switch would be // executed the following code is run
                    alert ("opened sidebar");

                    return;
                });
                   break;

             case 3:
// above alert only fire if case 3 block of code would be run , which is not suitable
break;
                   default:

}
    });
```

 i have defined     $(".sidebar.left").sidebar({side: "left"}); in init method , so the sidebar in general works , the only problem is comes from because i use  $(".sidebar.left").on("sidebar:opened", function () {
 inside a switch, i can't use break command inside that function , so i use return and break outside the function. the problem is when that case is fired by listener , it doesn't show alert message once the case is fired , it only trigger when i use another keycode (another case is fired)...

**Comment by IonicaBizau** [comment]
@pooyamoha Can you create a jsfiddle or jsbin to play with it?
