### ISSUE TITLE
Cant type text in textbox

### ISSUE THREAD

**Issue by pjp-97** [jillix/jQuery-sidebar#31]
I added some textboxes to the slider, but I can't type any text in them. Other things such as checkboxes and drop downs work, but not <input type='text'>

**Comment by IonicaBizau** [comment]
Hi @pjp-97! 

Thanks for your bug report! Can you please provide a jsFiddle or demo to reproduce this behavior?

**Comment by pjp-97** [comment]
I actually found the problem. I don't know why, but the text color in all the text boxes on the slider was set to white(against a white background). I set the color to black and now I can type in the text boxes no problem

**Comment by IonicaBizau** [comment]
Ah, makes sense. :grin: :+1:
