### ISSUE TITLE
Is it mobile responsive ?

### ISSUE THREAD

**Issue by lakinmohapatra** [jillix/jQuery-sidebar#32]
Is it mobile responsive ?

**Comment by IonicaBizau** [comment]
It should be, but that really depends on your page source code. I don't think the demo is very mobile friendly, but as long your page is mobile responsive, the sidebar will be too. 😁

**Comment by lakinmohapatra** [comment]
Thanks a lot for the information.

On Nov 27, 2017 9:47 PM, "Ionică Bizău (Johnny B.)" <
notifications@github.com> wrote:

Closed #32 <https://github.com/jillix/jQuery-sidebar/issues/32>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jillix/jQuery-sidebar/issues/32#event-1359582366>, or mute
the thread
