### ISSUE TITLE
it doesnt work with bootstrap modals.

### ISSUE THREAD

**Issue by fatihtoprak** [jillix/jQuery-sidebar#33]
have you ever test with bootstrap modals ?

`<a href="javascript:void(0);" data-toggle="modal"
                                data-target="#RegisterModal" id="newBtn">register</a>`

if sidebars plugin included, it doesnt work via, data attr.

**Comment by IonicaBizau** [comment]
I assume it's because of `javascript:void(0);`, but I'm not sure. It would help if you posted your code. :smile:
