### ISSUE TITLE
Jillix is not working.

### ISSUE THREAD

**Issue by asaphbran** [jillix/jQuery-sidebar#34]
I setted up the whole thing just like is shown in the docs and it just doesn't work. 

As you can see, I'm using JQuery and the latest version of the plugin and the CSS you posted as an example.

![image](https://user-images.githubusercontent.com/52551192/60733096-8ff57780-9f11-11e9-9cd4-aef21623a58c.png)

**Comment by sheksushant** [comment]
It has been over 1.5 years and it's still not working.

**Comment by IonicaBizau** [comment]
I am sorry for the late reply.

Just checked this and created two quick demos:

 - left sidebar: https://jsfiddle.net/rs453td2/
 - right sidebar: https://jsfiddle.net/rs453td2/1/

Let me know if you have any issues with this. ✨ 

Best!
